general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /usr/share/wallpapers/cachyos-wallpapers/CachyOS_Moon.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
    contrast = 0.9
}

# Clock
label {
    monitor =
    text = $TIME
    color = rgba(00d4ffee)
    font_size = 72
    font_family = FantasqueSansM Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(c8a84bcc)
    font_size = 18
    font_family = FantasqueSansM Nerd Font
    position = 0, 40
    halign = center
    valign = center
}

# Input field
input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.28
    dots_spacing = 0.18
    outer_color = rgba(00d4ff55)
    inner_color = rgba(04081499)
    font_color = rgba(b0ccd8ff)
    fade_on_empty = true
    placeholder_text = <i>password</i>
    hide_input = false
    check_color = rgba(00d4ffcc)
    fail_color = rgba(ff444499)
    fail_text = <i>wrong password</i>
    capslock_color = rgba(c8a84bcc)
    position = 0, -60
    halign = center
    valign = center
    rounding = 4
}
